#! /usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Deck\Command\DeckCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new DeckCommand());
$app->run();